server:
  port: 9090
spring:
  application:
    name: personnel-management-system-docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/management_system?useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  redis:
    database: 0
    host: redis://redis:6379
  mail:
    host: smtp.qq.com
    username: 1057240821@qq.com
    password: rdaptnznzeezbfde
    default-encoding: UTF-8
    port: 587

storage:
  location: /PersonnelManagement/storage
email:
  username: 1057240821@qq.com