version: '3.7'
services:
  web:
    image: personnel_management:latest
    networks:
      - personnel-management
    depends_on:
      - mysql
      - redis
    ports:
      - 3333:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources/application.yml:/app/resources/application.yml:ro
    restart: always

  redis:
    image: redis
    networks:
      - personnel-management
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - personnel_management_redis_data:/data
    restart: always

  mysql:
    image: mysql
    networks:
      - personnel-management
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - personnel_management_mysql_data:/var/lib/mysql
      - /root/PersonnelManagement-storage:/PersonnelManagement/storage
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

networks:
  personnel-management:
    external: true

volumes:
  personnel_management_mysql_data:
    external: true
  personnel_management_redis_data:
    external: true


