version: '3.7'
services:
  web:
    image: personnel-management/abouerp:latest
    networks:
      - textbook
    depends_on:
      - mysql
    ports:
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources/application.yml:/app/resources/application.yml:ro
    restart: always

  mysql:
    image: mysql
    networks:
      - textbook
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - textbook_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

networks:
  textbook:
    external: true

volumes:
  textbook_mysql_data:
    external: true

